name: Release
description: Release a new npm package
inputs:
  npm:
    description: npm token
    required: true
runs:
  using: composite
  steps:
    - name: Enable pnpm
      run: corepack enable
      shell: sh
    - name: Publish to NPM
      run: |
        pnpm config set //registry.npmjs.org/:_authToken ${{ inputs.npm }}
        pnpm publish --access public --no-git-checks
      shell: sh
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm }}
