name: lint
on:
  push:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.6.0
      - name: Setup Node.js
        uses: re-taro/actions/setup-node@v3.2.2
        with:
          node-version-file: .tool-versions
      - name: lint
        run: pnpm run lint
