name: lint
on:
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
      - name: Setup Node.js
        uses: re-taro/actions/setup-node@v3.7.7
        with:
          node-version-file: .tool-versions
      - name: lint
        run: pnpm lint
