name: release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          include-v-in-tag: false
      - if: ${{ steps.release.outputs.release_created }}
        uses: re-taro/actions/npm-publish@v3.4.1
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
