name: release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.3.0
      - id: release
        uses: googleapis/release-please-action@v4.3.0
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json
      - if: ${{ steps.release.outputs.release_created }}
        uses: re-taro/actions/npm-publish@v3.7.9
        with:
          npm-token: ${{ secrets.NPM_TOKEN }}
